spring.application.name=ability-platform
spring.datasource.url=jdbc:postgresql://postgres:5432/ability_system
spring.datasource.username=ability
spring.datasource.password=2729
spring.jpa.hibernate.ddl-auto=update
server.port=8080